spring:
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/hr_user}
    username: ${USER_DB_USERNAME:hr}
    password: ${USER_DB_PASSWORD:hr}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: ${USER_DB_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  h2:
    console:
      enabled: false
