# Port of the microservice
server:
  port: 8081

# Secret for the JWT signing
jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: false

spring:
  application:
    name: AUTHENTICATION-SERVICE
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:./authentication-microservice/sem_authentication;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

bootstrap:
  admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:true}
    net-id: ${BOOTSTRAP_ADMIN_NET_ID:ADMIN}
    password: ${BOOTSTRAP_ADMIN_PASSWORD}
