# Port of the microservice
server:
  port: 8083

spring:
  application:
    name: CONTRACT-SERVICE
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:./contract/microservice/contract;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Secret for the JWT signing
jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: true
